### ISSUE TITLE
什么时候适配 nodejs json 单文件保存呢？

### ISSUE THREAD

**Issue by rxliuli** [akirarika/kurimudb#14]

**Comment by akirarika** [comment]
这个还没确定！！这个应该排在比较后面的呜呜呜

如果想在 electron 中用的话，可以先用 indexeddb，可能缺点就是 Api 是异步的

**Comment by rxliuli** [comment]
不是在 electron 里面，是一个 vscode 插件，希望存几张数据表（以 json 单文件的形式，不希望引入数据库）

**Comment by akirarika** [comment]
> 不是在 electron 里面，是一个 vscode 插件，希望存几张数据表（以 json 单文件的形式，不希望引入数据库）

这样压，实在着急的话，可以试着自己实现下一个简易的驱动，可以参考 [LocalStorage](https://github.com/akirarika/kurimudb/blob/master/drivers/kurimudb-driver-localstorage/index.ts)  的实现方式，和这个 [PR](https://github.com/akirarika/kurimudb/pull/10)~

**Comment by rxliuli** [comment]
这，简单看了一下。。。虽然吾辈也能理解是轻量级，不过不区分操作直接 write 进去可还行
